/*
 * SwizzleVec3Op4.h
 * 
 * This file is part of the "GaussianLib" project (Copyright (c) 2015 by Lukas Hermanns)
 * See "LICENSE.txt" for license information.
 */

// THIS FILE MUST NOT HAVE A HEADER GUARD!

__GS_SWIZZLE_REF4__(x,x,x,z)
__GS_SWIZZLE_REF4__(x,x,y,z)
__GS_SWIZZLE_REF4__(x,x,z,x)
__GS_SWIZZLE_REF4__(x,x,z,y)
__GS_SWIZZLE_REF4__(x,x,z,z)
__GS_SWIZZLE_REF4__(x,y,x,z)
__GS_SWIZZLE_REF4__(x,y,y,z)
__GS_SWIZZLE_REF4__(x,y,z,x)
__GS_SWIZZLE_REF4__(x,y,z,y)
__GS_SWIZZLE_REF4__(x,y,z,z)
__GS_SWIZZLE_REF4__(x,z,x,x)
__GS_SWIZZLE_REF4__(x,z,x,y)
__GS_SWIZZLE_REF4__(x,z,x,z)
__GS_SWIZZLE_REF4__(x,z,y,x)
__GS_SWIZZLE_REF4__(x,z,y,y)
__GS_SWIZZLE_REF4__(x,z,y,z)
__GS_SWIZZLE_REF4__(x,z,z,x)
__GS_SWIZZLE_REF4__(x,z,z,y)
__GS_SWIZZLE_REF4__(x,z,z,z)

__GS_SWIZZLE_REF4__(y,x,x,z)
__GS_SWIZZLE_REF4__(y,x,y,z)
__GS_SWIZZLE_REF4__(y,x,z,x)
__GS_SWIZZLE_REF4__(y,x,z,y)
__GS_SWIZZLE_REF4__(y,x,z,z)
__GS_SWIZZLE_REF4__(y,y,x,z)
__GS_SWIZZLE_REF4__(y,y,y,z)
__GS_SWIZZLE_REF4__(y,y,z,x)
__GS_SWIZZLE_REF4__(y,y,z,y)
__GS_SWIZZLE_REF4__(y,y,z,z)
__GS_SWIZZLE_REF4__(y,z,x,x)
__GS_SWIZZLE_REF4__(y,z,x,y)
__GS_SWIZZLE_REF4__(y,z,x,z)
__GS_SWIZZLE_REF4__(y,z,y,x)
__GS_SWIZZLE_REF4__(y,z,y,y)
__GS_SWIZZLE_REF4__(y,z,y,z)
__GS_SWIZZLE_REF4__(y,z,z,x)
__GS_SWIZZLE_REF4__(y,z,z,y)
__GS_SWIZZLE_REF4__(y,z,z,z)

__GS_SWIZZLE_REF4__(z,x,x,x)
__GS_SWIZZLE_REF4__(z,x,x,y)
__GS_SWIZZLE_REF4__(z,x,x,z)
__GS_SWIZZLE_REF4__(z,x,y,x)
__GS_SWIZZLE_REF4__(z,x,y,y)
__GS_SWIZZLE_REF4__(z,x,y,z)
__GS_SWIZZLE_REF4__(z,x,z,x)
__GS_SWIZZLE_REF4__(z,x,z,y)
__GS_SWIZZLE_REF4__(z,x,z,z)
__GS_SWIZZLE_REF4__(z,y,x,x)
__GS_SWIZZLE_REF4__(z,y,x,y)
__GS_SWIZZLE_REF4__(z,y,x,z)
__GS_SWIZZLE_REF4__(z,y,y,x)
__GS_SWIZZLE_REF4__(z,y,y,y)
__GS_SWIZZLE_REF4__(z,y,y,z)
__GS_SWIZZLE_REF4__(z,y,z,x)
__GS_SWIZZLE_REF4__(z,y,z,y)
__GS_SWIZZLE_REF4__(z,y,z,z)
__GS_SWIZZLE_REF4__(z,z,x,x)
__GS_SWIZZLE_REF4__(z,z,x,y)
__GS_SWIZZLE_REF4__(z,z,x,z)
__GS_SWIZZLE_REF4__(z,z,y,x)
__GS_SWIZZLE_REF4__(z,z,y,y)
__GS_SWIZZLE_REF4__(z,z,y,z)
__GS_SWIZZLE_REF4__(z,z,z,x)
__GS_SWIZZLE_REF4__(z,z,z,y)
__GS_SWIZZLE_REF4__(z,z,z,z)



// ================================================================================
